extends RefCounted
## schemas/player_report.schema.json is the only field/enum contract.
const Validator = preload("res://sdk/roomkit/shared/schema_validator.gd")
const SCHEMA := "res://schemas/player_report.schema.json"
const MAX_BYTES := 12000
const MAX_RECORDS := 32
const WINDOW_MS := 120000
static var _record_schema: Dictionary = {}

static func record_schema() -> Dictionary:
	if _record_schema.is_empty():
		var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(SCHEMA))
		if parsed is Dictionary:
			_record_schema = parsed.get("$defs", {}).get("record", {})
	return _record_schema

static func clean_record(metrics: Dictionary) -> Dictionary:
	var clean := {}
	var fields: Dictionary = record_schema().get("properties", {})
	for key in fields:
		# Metadata is generated by the collector, never copied from caller input.
		if key in ["utc", "monotonic_ms", "session_id", "build", "kind"]:
			continue
		if metrics.has(key) and Validator.validate(metrics[key], fields[key]) == "":
			clean[key] = metrics[key]
	clean.phase = clean.get("phase", "IDLE")
	clean.error = clean.get("error", "OTHER")
	return clean

static func validate(report: Variant) -> bool:
	return report is Dictionary and Validator.validate_file(report, SCHEMA) == "" and JSON.stringify(report).to_utf8_buffer().size() <= MAX_BYTES

static func platform() -> String:
	return OS.get_name() if OS.get_name() in ["Windows", "Linux"] else "Other"

static func valid_email(value: Variant) -> bool:
	if not value is String or value.length() > 254:
		return false
	for index in value.length():
		if value.unicode_at(index) <= 32 or value.unicode_at(index) >= 127:
			return false
	var pattern := RegEx.new()
	pattern.compile("^[A-Za-z0-9][A-Za-z0-9._+-]{0,63}@[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$")
	return pattern.search(value) != null

static func _metric(record: Dictionary, key: String, unit: String = "") -> String:
	if key == "reliable_loss_percent" and (record.get("loss_state", "") != "available" or int(record.get("loss_sample_count", 0)) <= 0):
		return "未知"
	return "未知" if not record.has(key) else ("%.2f" % float(record[key])).trim_suffix("0").trim_suffix("0").trim_suffix(".") + unit

## Entirely local human-readable clipboard report, bounded by validated input.
static func summary(report: Dictionary) -> String:
	if not validate(report):
		return ""
	var records: Array = report.records
	var first: Dictionary = records[0]
	var last: Dictionary = records[-1]
	var marks := 0
	for record in records:
		if record.kind == "mark":
			marks += 1
	var lines := PackedStringArray(["RoomKit 脱敏诊断摘要", "报告编号：" + report.report_id, "平台：" + report.platform + "；版本：" + str(last.build), "UTC：" + str(first.utc) + " 至 " + str(last.utc), "记录：%d 条；卡顿标记：%d" % [records.size(), marks], "仅含白名单诊断数据，无账号、密码、IP 或文件路径；不能据此直接判断卡顿原因。"])
	lines.append("丢包估计仅指 ENet 可靠发送，不代表全部 UDP 或下行快照丢失率。")
	for record in records:
		lines.append("%s %s %s/%s FPS %s 帧 %s RTT %s 更新间隔 %s 未更新 %s 丢包估计 %s" % [record.utc, "标记" if record.kind == "mark" else "采样", record.phase, record.error, _metric(record, "fps"), _metric(record, "frame_max_ms", "ms"), _metric(record, "rtt_ms", "ms"), _metric(record, "snapshot_interval_ms", "ms"), _metric(record, "snapshot_age_ms", "ms"), _metric(record, "reliable_loss_percent", "%")])
	return "\n".join(lines)

## mailto is a draft handoff only; no mail account, password, SMTP or upload.
## Cap the entire percent-encoded URI, not the unencoded Chinese body.
static func mailto(report: Dictionary, recipient: String) -> String:
	if not validate(report) or not valid_email(recipient):
		return ""
	var latest: Dictionary = {}
	var marks := 0
	for record in report.records:
		if record.kind == "sample":
			latest = record
		else:
			marks += 1
	var body := "RoomKit 脱敏诊断\n编号 %s\n平台 %s；%d 条记录，%d 个卡顿标记\n" % [report.report_id, report.platform, report.records.size(), marks]
	if not latest.is_empty():
		body += "UTC %s\nFPS %s；帧 %s；RTT %s\n更新 %s；未更新 %s；丢包估计 %s\n" % [latest.utc, _metric(latest, "fps"), _metric(latest, "frame_max_ms", "ms"), _metric(latest, "rtt_ms", "ms"), _metric(latest, "snapshot_interval_ms", "ms"), _metric(latest, "snapshot_age_ms", "ms"), _metric(latest, "reliable_loss_percent", "%")]
	body += "丢包估计仅指 ENet 可靠发送，不代表全部 UDP 或下行快照。\n详细摘要可复制，JSONL 可手动附加。请确认后发送。"
	var uri := "mailto:" + recipient + "?subject=" + "RoomKit 诊断报告".uri_encode() + "&body=" + body.uri_encode()
	if uri.to_utf8_buffer().size() > 1800:
		body = "RoomKit 脱敏诊断\n编号 " + report.report_id + "\n请将客户端复制的诊断摘要粘贴到此处，确认后发送。"
		uri = "mailto:" + recipient + "?subject=" + "RoomKit 诊断报告".uri_encode() + "&body=" + body.uri_encode()
	return uri if uri.to_utf8_buffer().size() <= 1800 else ""
